name: cims
channels:
  - conda-forge
dependencies:
  - python>=3.11
  - jupyter
  - matplotlib
  - seaborn>=0.13.2
  - numpy
  - polars
  - pyarrow
  - pandas>=2
  - pip
  - scipy
  - setuptools
  - networkx
  - xlrd
  - pip:
    - pyxlsb
