project:
  type: book
  output-dir: _book

book:
  title: CIMS
  author: Brad Griffin, Jillian Anderson, and Matt Sniatynski
  # logo: altair-hist.png
  repo-url: https://github.com/EMRG-SFU/cims
  repo-branch: quarto_docs
  repo-actions: [issue]
  # sharing: [twitter, facebook]
  chapters:
    - index.md
    - part: install.qmd
      chapters:
        - GettingStarted.qmd
        - chapter-1.qmd
    - part: model.qmd
      chapters:
        - chapter-2.qmd
        - chapter-3.qmd
        - chapter-5.qmd
    - part: outputs.qmd
      chapters:
        - chapter-4.qmd
        - chapter-5.qmd

format:
  html:
    theme: cosmo