project:
  type: book
  output-dir: _book

book:
  title: CIMS
  author: Brad Griffin, Jillian Anderson, and Matt Sniatynski
  # logo: altair-hist.png
  repo-url: https://github.com/EMRG-SFU/cims
  repo-branch: quarto_docs
  repo-actions: [issue]
  # sharing: [twitter, facebook]
  chapters:
    - index.qmd
    - part: install
      chapters:
        - getting_started.qmd
    - part: model
      chapters:
        - overview.qmd
        - technologies.qmd
        - sectors.qmd
    - part: results
      chapters:
        - policies.qmd
        - outputs.qmd

format:
  html:
    theme: cosmo