# Introduction to CIMS

## Background and model objectives

CIMS[^1] is an integrated set of economic, energy, and materials models
designed to provide information to policy makers on the likely response
of firms and households to policies that influence their technology
acquisition and technology use decisions.[^2] Thus, it is sometimes
described as a technology simulation model, which seeks to reflect how
people actually behave rather than how they ought to behave.[^3] CIMS is
able to provide policy makers with information on: (1) the ability of
their policies to achieve specific objectives (like greenhouse gas (GHG)
emissions reductions), (2) the likely costs of achieving these
objectives, and (3) the uncertainties associated with the model's
simulations. CIMS is maintained and operated by the Energy and Materials
Research Group at the School of Resource and Environmental Management at
Simon Fraser University.

[^1] CIMS originally stood for Canadian Integrated Modelling System but, as the model is now being applied to other countries, the acronym is now used as a proper name.

CIMS is based on energy flows through a country's economic system. Like
its predecessor, the ISTUM family of models, which form the individual
sub-components of CIMS, it tracks the flow of energy, beginning with
energy services and production processes through to eventual end-use by
individual technologies. Unlike the partial equilibrium ISTUM models,
which compete technologies against each other to serve pre-specified
demands for end-uses, CIMS is nearly a full equilibrium system that
allows the practitioner to include price driven energy and goods and
services supply and demand equilibrium, energy trade, and some indirect
macroeconomic effects, specifically disposable income and savings
multiplier effects.

CIMS' focus on energy flows through technologies makes it ideal for
modelling policies intended to affect energy efficiency, greenhouse gas
emissions, and air quality. Fuel consumption and emissions of all
pollutants are technology specific; unless a model operates on a
detailed technology basis, as CIMS does, fuel consumption and emission
estimates can only be approximated by economic activity.

TODO: Discuss model operational structure (Excel input, Python, Excel
results)

TODO: Model licenses (MIT & CC4.0)

TODO: Split repository into code and data

## Model Scale and Scope

CIMS covers the entire Canadian economy and can connect to an aggregated
representation of the US economy. The Canadian version of CIMS currently
includes six provinces and an aggregation of the Atlantic Provinces.[^4]
[Table 1](#_Ref61957786) illustrates the sectors and regions covered in
CIMS.

TODO: Separate out Atlantic provinces (medium priority) and Territories
(lower priority)

  ------------------------------------------------------------------------------------
  **Sectors**            **BC**   **AB**   **SK**   **MB**   **ON**   **QC**   **AT**
  --------------------- -------- -------- -------- -------- -------- -------- --------
  Residential              X        X        X        X        X        X        X

  Commercial               X        X        X        X        X        X        X

  Transportation           X        X        X        X        X        X        X
  Personal                                                                    

  Transportation           X        X        X        X        X        X        X
  Freight                                                                     

  Mining                   X                 X        X        X        X        X

  Coal Mining              X        X        X                                   X

  Natural Gas              X        X        X        X        X        X        X
  Extraction                                                                  

  Petroleum Crude          X        X        X                 X                 X

  Petroleum Refining       X        X        X                 X        X        X

  Industrial Minerals      X        X                          X        X        X

  Iron and Steel                                               X        X     

  Metal Smelting           X                          X        X        X        X

  Chemical Products        X        X        X                 X        X     

  Pulp and Paper           X        X                          X        X        X

  Other Manufacturing      X        X        X        X        X        X        X

  Waste                    X        X        X        X        X        X        X

  Agriculture              X        X        X        X        X        X        X
  ------------------------------------------------------------------------------------

  : : CIMS Sectors for Canada

TODO: Include major cities as separate nodes under provinces?

- Would include Toronto, Montreal, and Vancouver only. Use metro region
  or city only? Is the reason for this to represent city policies?

While the model is simple in operation, it can appear complex because it
is technologically explicit and covers the whole economy. CIMS
represents a detailed list of technologies (fridges, light bulbs, cars,
industrial motors, steel furnaces, buildings, power plants, etc.), and
includes their linkages to each other. The model is especially large for
the industrial sectors because industry has the largest variety of
technologies.

CIMS highlights the interplay of energy supply and demand because
energy-related GHG emissions are currently a key policy concern. Thus,
the model focuses on the interaction between sectors that use energy
(industrial, residential, commercial / institutional, and transportation
sectors) and sectors that produce or transform energy (electricity
generation, fossil fuel supply, oil refining, natural gas processing,
biofuels, and hydrogen). This interaction is shown in [Figure
1](#_Ref61957705). A policy that seeks to influence energy supply and
demand may also influence the cost of producing goods and services, thus
affecting their price and final demand. To reflect these interactions,
CIMS includes a goods and services final demand feedback loop, composed
of Armington elasticities for traded goods and empirically driven
relationships between the traded and non-traded sectors.

![Figure 1. Overall Diagram of
CIMS](media/image2.svg){width="4.5316458880139985in"
height="4.377740594925634in"}

## Model Simulation: Six Steps

As a simulation model, CIMS simulates the evolution of technologies
acquired to meet energy services, and it uses both engineering and
economic information. The engineering information details the unit
energy consumption of each energy service technology and explains, using
flow models of technologically heterogeneous sectors, how final energy
service demands, intermediate products, and energy supply are related.
The economic information determines which technologies are preferable in
terms of cost minimization. While CIMS is not an optimization model, it
can be adapted to produce results like those of an optimization model by
calling on certain built-in functions. These functions are known as
winner-take-all functions, and they give all new market shares in a
given competition to the technology or process with the least cost.

TODO: Review Winner-take-all function and decide if necessary

CIMS is designed to mimic a sector or industry by representing a number
of industrial establishments, residential or commercial buildings, and
delivery of goods or personal travel within a defined region. The model
focuses its analysis on the aggregate energy end-use requirements of
that industry or sector. For example, in industry the major end-uses are
process heat, motive force, space heat, and lighting. In the pulp and
paper sector, the major end-uses are steam heat or mechanical energy to
digest wood fibre into pulp, mechanical energy to convey and form pulp
into paper, mechanical energy to press moisture out of formed pulp or
paper, steam heat to dry pulp or paper, space heat, and lighting. In
residential and commercial buildings, the primary end-uses include space
heating and cooling, hot water production, refrigeration, and other
assorted appliances.

**A CIMS simulation comprises six basic steps:**

1.  The baseline macro-economic drivers, energy supply drivers, and
    energy service technology characteristics are set for the desired
    time frame (15 years, 20 years, etc.) in five-year increments.

    a.  Technologies are represented in the model in terms of the
        quantity of energy service they provide. This could be, for
        example, vehicle kilometers traveled, tonnes of paper, or square
        metres of floor space heated and cooled. Then, a forecast of
        growth in energy service demand is used to drive future demand
        for energy services, usually in five-year increments.

    b.  Macro-economic drivers include income, economic output,
        structural evolution of sectors, interest rates, employment
        rates, regulations, etc. They account for all energy service
        demands in the energy demand module.

    c.  Energy supply drivers include international commodity prices,
        domestic market developments, forecasts of costs and
        availability of marginal energy supplies, and the resulting
        forecasts of domestic prices.

    d.  Energy service technology characteristics include the date a
        technology or process will be available, technology energy
        efficiencies and capital / operating costs, firm and household
        time preferences (discount rates) for discretionary and
        non-discretionary expenditures (new and retrofit), and other
        behavioural parameters (perceived risks and consumer surpluses
        of different technologies, interdependence of certain technology
        choices that serve different energy services, such as domestic
        water heating and domestic space heating).

2.  The energy demand module (industry, commercial, residential, and
    transportation) is run for the initial driver values (including
    energy supply prices).

    a.  In each future period, a portion of the initial year's stock of
        technologies is retired. Retirement depends only on age. The
        remaining technology stocks in each period are subtracted from
        the forecast energy service demand and this difference
        determines the amount of new technology stocks in which to
        invest.

    b.  Prospective energy service technologies compete to fill the new
        service demand. The objective of the model is to simulate this
        competition so that the outcome approximates what would happen
        in the real world. Here the model relies heavily on market
        research of past and prospective firm and household behavior.
        Technology costs depend on recognized and financial costs, but
        also on identified differences in non-financial preferences
        (e.g., differences in the quality of lighting from different
        light bulbs) and risks (one technology is seen as more likely to
        fail than another). Even the determination of financial costs is
        not straightforward as time preferences (discount rates) can
        differ depending on the decision maker (household vs. firm) and
        the type of decision (non-discretionary vs. discretionary).
        Consequently, the competition is simulated probabilistically;
        new stock purchases are distributed among prospective
        technologies with financial costs being just one of several
        factors in determining market share.

    c.  In each period, a similar competition occurs with remaining
        technology stocks to simulate retrofitting (if desirable and
        likely from the firm or household's perspective). The same
        financial and non-financial information is required, except that
        the capital costs of remaining technology stocks are excluded,
        having been spent earlier when the remaining technology stock
        was originally acquired.

3.  The demand models then send their requirements for energy to the
    energy supply models. The supply models send back corresponding
    energy prices. If the changes in energy prices are over a set
    threshold value for equilibrium (usually 5%), the demand models are
    then rerun with the new energy prices. This process is repeated
    until all energy price changes fall under the threshold value.
    Figure 2 describes this process:

![Figure 2. CIMS\' Energy Supply and Demand Flow
Model](media/image3.png){width="5.89375in"
height="3.6333333333333333in"}

4.  Policy or market driven energy price changes may change the
    lifecycle cost of some energy services, thereby changing the end-use
    price for these services. If the change in lifecycle cost from the
    business-as-usual case is beyond a pre-set threshold price
    elasticities for these services are applied, thereby changing the
    demand for these services. This new demand is sent back to the
    supply and demand models for re-calculation.

5.  The model reiterates step 2, 3 and 4 until all variables stabilize.
    It then proceeds to the next time period. Steps 1 through 5 are
    repeated for all time periods.

6.  Output: Output is provided for total capital stock, new capital
    stock, fuel use, service use, emissions, levelized costs by
    technology, and energy service prices.

    a.  **Sub-model Outputs**

        i.  Annualized lifecycle costs by sector by year by technology
            based on behavioural discount rates (20-80%) (See Table 5).

        ii. Fuel use and emissions by sector by year by technology.

        iii. Service and auxiliary use by sector by year by technology.

        iv. Total stock use by sector by year by technology.

        v.  New stock use by sector by year by technology.

        vi. Retrofits by sector by year by technology.

        vii. Technology cost changes due to declining capital cost
             function

    b.  **Supply and Demand Feedback Outputs**

        i.  Annualized lifecycle cost per unit produced for all sectors
            by year based on financial cost of capital for both the BAU
            and Policy case; the model operator sets the cost of capital
            (e.g. 7.5 or 10%)

        ii. BAU and Policy final demand for each sector\'s product or
            service by year.

        iii. BAU and Policy disaggregated energy demand for all sectors
             by year.

        iv. Changes in disaggregated capital, operations and
            maintenance, and energy costs by sector by year.

        v.  Changes in GHGs and selected criteria air contaminants
            (CACs), energy and service use by technology, sorted by
            technology competition, for BAU and Policy by sector by
            year.

        vi. Changes in net exports of key energy commodities from BAU to
            Policy

        vii. Changes in energy prices by year

        viii. Changes in the financial cost of production split into the
              cost of production and demand effects for industry and
              manufacturing

        ix. Changes consumers' surplus for personal transportation and
            residences

        x.  Changes in value-added for industry and manufacturing

TODO: Model currently equilibrates only through prices. Could we also
find quantity equilibrium for cap system?

- Would need special market (?) for emissions cap that doesn't need
  specific service requests

  - Include emissions from all capped sectors in market

  - Iterate carbon price until emissions match cap

  - Use shadow price like for DAC? Iterate between max quantity cap and
    min tax price at each node

  - 🡪 can we generalise this for DAC, trading cap, any quantity max

- Is this worth the effort or just iterate carbon price manually?
